In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn import svm
import seaborn as sns
from matplotlib.colors import ListedColormap
from sklearn import neighbors
import pandas_datareader.data as web
import matplotlib.pyplot as plt
from pandas.plotting import parallel_coordinates
from sklearn.preprocessing import StandardScaler
from sklearn import decomposition
import scipy
from sklearn.manifold import TSNE
import seaborn as sn
from sklearn.datasets import make_friedman1
from sklearn.decomposition import SparsePCA
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.neighbors import NearestNeighbors

In [132]:
#dataread

VC_df = pd.read_csv('Q3/vehicles.csv')
#dataread

AAPL_df = pd.read_csv('Q3/AAPL_n.csv')
AAPL_df = AAPL_df.drop(['Date'], axis = 1)
OTM_df = pd.read_csv('Q3/OptionDataOTM_data.csv')

In [119]:
VC_df = AAPL_df

In [134]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

def doPCA(data):
  #data = data.drop(['Date'], axis = 1)
  norm = StandardScaler().fit_transform(data)
  pca = PCA(n_components=3)
  newdata = pca.fit_transform(norm)
  return newdata,pca

npca, pc = doPCA(VC_df)

In [135]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

def doPCA1(data):

  norm = StandardScaler().fit_transform(data)
  pca = PCA()
  newdata = pca.fit_transform(norm)
  return newdata,pca

npca1, pc1 = doPCA1(VC_df)

In [136]:
def doTSNE(data,k):
    
    l = data.index
    
    s_data = StandardScaler().fit_transform(data)

    model = TSNE(n_components = 3 , perplexity=k, random_state = 0)

    tsne_data = model.fit_transform(s_data)

    
    return tsne_data

ntsne = doTSNE(VC_df,10)
data = StandardScaler().fit_transform ( VC_df.to_numpy()  )

In [137]:
def doTSNE1(data,k):

    l = data.index
    s_data = StandardScaler().fit_transform(data)

    model = TSNE( perplexity=k, random_state = 0)

    tsne_data = model.fit_transform(s_data)

    #tsne_data = np.vstack((tsne_data.T, l)).T
    
    return tsne_data

ntsne1 = doTSNE1(VC_df,30)

In [16]:
data[0]

array([-0.36273813, -0.42412032, -0.27927483, -0.23953507,  0.        ,
       -0.50242132, -0.56640896,  0.5342275 ,  0.47954631,  0.36782701,
        0.16320723,  0.15042407, -0.44004349, -0.57980621,  0.49290474,
        1.10042148,  0.91058658,  0.21507724])

In [ ]:
def get10NN(X):
    
    nbrs = NearestNeighbors(n_neighbors=10, algorithm='ball_tree').fit(X)
    distances, indices = nbrs.kneighbors(X)
    return indices

ind = get10NN(data)
ind

In [121]:
def get10NN(X):
    
    nbrs = NearestNeighbors(n_neighbors=10, algorithm='ball_tree').fit(X)
    distances, indices = nbrs.kneighbors(X)
    return indices

ind = get10NN(data)
ind

array([[   0,  390, 2730, ..., 2687, 5460, 4680],
       [   1,    6,   20, ...,  387,   11,  386],
       [   2,   20,   29, ...,  387,    1,    4],
       ...,
       [5847, 5835, 5844, ..., 5503, 5467, 5842],
       [5848, 5846, 5543, ..., 5507, 5074, 5490],
       [5849, 3119, 5845, ..., 5460, 3577, 1949]], dtype=int64)

In [122]:
len(ind)

5850

In [123]:
def get10NN(X):
    
    nbrs = NearestNeighbors(n_neighbors=10, algorithm='ball_tree').fit(X)
    distances, indices = nbrs.kneighbors(X)
    return indices

pcaind = get10NN(npca)
pcaind

array([[   0,  389,  390, ..., 1949, 3509,  429],
       [   1,    6,   20, ...,    2,  387,   11],
       [   2,   29,  226, ...,    5,    6,  386],
       ...,
       [5847, 1202, 1218, ..., 1215, 5844, 1212],
       [5848, 5846, 1201, ..., 1198, 1213, 4835],
       [5849, 1398, 5460, ..., 4680, 3119, 2730]], dtype=int64)

In [124]:
def get10NN(X):
    
    nbrs = NearestNeighbors(n_neighbors=10, algorithm='ball_tree').fit(X)
    distances, indices = nbrs.kneighbors(X)
    return indices

tsneind = get10NN(ntsne)
tsneind

array([[   0,  390, 2730, ..., 5460, 4290, 5070],
       [   1,    6,   20, ...,  363,  297,   29],
       [   2,   20,    6, ...,   29,   21,  363],
       ...,
       [5847, 5844, 5835, ..., 5503, 5836, 5492],
       [5848, 5846, 5507, ..., 4835, 5055, 4738],
       [5849, 1169, 3119, ..., 1949, 2339, 3577]], dtype=int64)

In [125]:
def comp(x,y):
    s = 0
    
    for i in range(0,len(x)):
        c = np.count_nonzero(x[i]==y[i])
        s = s+c
        
    return s
    
s = comp(ind,pcaind)
per = (s/(5850*10))*100
per

24.102564102564102

In [126]:
def comp(x,y):
    s = 0
    
    for i in range(0,len(x)):
        c = np.count_nonzero(x[i]==y[i])
        s = s+c
        
    return s
    
s = comp(ind,tsneind)
per = (s/(5850*10))*100
per

32.72991452991453

In [127]:
def comp(x,y):
    s = 0
    
    for i in range(0,len(x)):
        c = len(set(x[i]) & set(y[i]) )
        s = s+c
        
    return s
    
s = comp(ind,pcaind)
per = (s/(5850*10))*100
per

70.76923076923077

In [ ]:
per = (s/(387*10))*100
per

In [128]:
def comp(x,y):
    s = 0
    
    for i in range(0,len(x)):
        c = len(set(x[i]) & set(y[i]) )
        s = s+c
        
    return s
    
s = comp(ind,tsneind)
per = (s/(5850*10))*100
per

77.82564102564102

In [ ]:

euclidean_distances(data[0].reshape(1, -1),data[100].reshape(1, -1))

In [148]:
def comp(x):
    s = 0
    
    for i in range(0,len(x)):
        for j in range(0,len(x)):
            c = euclidean_distances(x[i].reshape(1, -1),x[j].reshape(1, -1))
            s = s+c
        
    return s/(len(x)*len(x))
    
s = comp(npca1)
s

array([[5.38484959]])

In [138]:
def comp(x):
    s = 0
    
    for i in range(0,len(x)):
        for j in range(0,len(x)):
            c = euclidean_distances(data[i].reshape(1, -1),data[j].reshape(1, -1))
            s = s+c
        
    return s/len(x)
    
s = comp(npca)
s

array([[2083.93679122]])